### ISSUE TITLE
can we move this to "digling"?

### ISSUE THREAD

**Issue by LinguList** [digling/calcblog#1]
woudl be nicer, in terms of consistency, for our projects...

**Comment by tresoldi** [comment]
I had actually suggested it in my email... ;)

**Comment by tresoldi** [comment]
For reasons of ownership, I apparently cannot request the transfer to digling (see https://github.com/go-gitea/gitea/issues/1797 )

I transferred to you, so you can move it yourself (sorry for the trouble)
