### ISSUE TITLE
2018 edition

### ISSUE THREAD

**Issue by tresoldi** [digling/calcblog#4]
I've just pushed the PDF combining my changes and yours: https://github.com/digling/calcblog/blob/master/calcblog.pdf

I would still like to read everything a single time (perhaps even in print), but if you prefer to get it rolling immediately I am happy enough with it. Just let me know (maybe we should show it to the other CALCies, including Gereon?)

**Comment by LinguList** [comment]
Please see my branch final-2018, there were still a lot of things to be fixed, specifically, there was a \small{ instead of a {\small, which caused the text to become small font halfways. So it shows how important it is to look at the actual PDF. I'd ask you to quietly check again, also see my small changes, that improvie layout, as we'll need them next time, add potential final changes, and I'll then submit this to hcommons.

**Comment by tresoldi** [comment]
Yes, I was working on that, had noticed the `small`. I will keep working here.

Do we have an internal deadline for this? Today?

**Comment by LinguList** [comment]
I'll submit on Wednesday. So if you want to keep looking at things, you have until tomorrow.

**Comment by tresoldi** [comment]
One thing I was considering was to add a footnote with the URL for all the `\url{}` and `\href{}` commands: in print, things like "you can find a GitHub Gist here" are strange/ugly.

As it is mostly a matter of searching for the dozen of so occurrences, it wouldn't take much time, it is more a matter of aesthetics. Your take?

**Comment by LinguList** [comment]
My take is very practical: this needs to get out, nobody will really care, if there's a hyperref, and people find original posts online.

**Comment by LinguList** [comment]
Just the things like the figures overfloating and other crap like the \small{ should not happen, of course.

**Comment by tresoldi** [comment]
I've fixed everything I could find, including giving a minimal consistency to the references. One important thing was to fix the code listings, as they had a number issues (even using curly quotes).

The placement of the floats might perhaps be improved, but I guess it is good enough right now -- at least there are no more things like table invading the reference subsection. Please take a look and let me know.

**Comment by tresoldi** [comment]
Oh yes, it is calcblog.pdf and calcblog.tex

**Comment by LinguList** [comment]
Thanks, I think it's good to go. I'll submit it tomorrow or on Wednesday.

**Comment by tresoldi** [comment]
Great, I'll get started with the 2019 once the new issues with CLICS are solved.
